### ISSUE TITLE
Failed to compile on RPi

### ISSUE THREAD

**Issue by TomasLife** [sensepost/mana#88]
I'm trying to compile this on my RaaspberryPi 2 B on Raspbian, but I always get this error:
../src/crypto/tls_openssl.c: In function ‘tls_load_ca_der’:
../src/crypto/tls_openssl.c:1540:40: error: dereferencing pointer to incomplete type ‘SSL_CTX {aka struct ssl_ctx_st}’
  lookup = X509_STORE_add_lookup(ssl_ctx->cert_store,
                                        ^~
../src/crypto/tls_openssl.c: In function ‘tls_connection_get_keys’:
../src/crypto/tls_openssl.c:2532:24: error: dereferencing pointer to incomplete type ‘SSL {aka struct ssl_st}’
  if (ssl == NULL || ssl->s3 == NULL || ssl->session == NULL)

I have tried to compile with the hostapd branch 2.6 but I get this error!
